### ISSUE TITLE
Create dropdown for theme changer and fix the dropdown bug

### ISSUE THREAD

**Issue by ItsGamingTube** [WybeNetwork/VistaPanel-Customizations#12]

**Comment by mahofficial** [comment]
We will look into it soon

**Comment by mahofficial** [comment]
It seems like that there is some sort of bug with the dropdown of theme switcher and we will soon start working on it to fix it.

**Comment by 4yx** [comment]
What exactly is the problem? It works fine for me.
Could you please provide a description?

**Comment by mahofficial** [comment]
> What exactly is the problem? It works fine for me.
> Could you please provide a description?

When added to the right sidebar the stylesheet doesn't load on other pages but when added in the footer area it is not possible to choose between themes. (After testing I found out these things), so they need a fix I believe.

And yeah, I wasn't able to understand what bug the author of this issue is referring to.

**Comment by 4yx** [comment]
Thanks. I found a fix, will be updating README soon. It's fixing part of the issue, but it should work.

**Comment by ItsGamingTube** [comment]
No it's not fixed.
See my new issue thred for more info.

**Comment by mahofficial** [comment]
> No it's not fixed.
> See my new issue thred for more info.

Kindly refer to this section of readme.md file https://github.com/WybeNetwork/VistaPanel-Customizations/tree/master/theme-switcher#how-can-i-install-use-it
