### ISSUE TITLE
Responsive Domain Searcher Using Wrong Referral Code

### ISSUE THREAD

**Issue by finley541** [WybeNetwork/VistaPanel-Customizations#20]
I am trying to use the referral code `29044` but it uses the referral code `25147` instead. Any help would be great! My code in the top advert:

```
<link rel="stylesheet" type="text/css" href="https://vpt.cdn.wybenetwork.com/dark-lite/icon_spritemap.css">
<link rel="stylesheet" type="text/css" href="https://vpt.cdn.wybenetwork.com/dark-lite/styles.css">

<script type="text/javascript">
	var affCode = '29044';
</script>
<script src="https://cdn.jsdelivr.net/gh/VPTOfficial/VistaPanel-Customizations/responsive-domain-search/responsive-domain-search.js" type="text/javascript"></script>
```

**Comment by 4yx** [comment]
cc @PlanetTheCloud: is it possible the two scripts are loaded at the same time, which results in the first check the script makes (if "affCode" is undefined) to be always true?

**Comment by PlanetTheCloud** [comment]
I've tested this and it is working just fine here
![image](https://user-images.githubusercontent.com/35788716/152287388-9139145b-96f0-44b5-9ac1-f2fe38fe6cc6.png)
(it is false, which means affcode won't be changed).
Can you make sure that the code has been loaded properly? Go to your control panel, view page source (Ctrl + U) and then find (Ctrl + F) the "var affCode". Let me know what you see.

**Comment by 4yx** [comment]
> I've tested this and it is working just fine here ![image](https://user-images.githubusercontent.com/35788716/152287388-9139145b-96f0-44b5-9ac1-f2fe38fe6cc6.png) (it is false, which means affcode won't be changed). Can you make sure that the code has been loaded properly? Go to your control panel, view page source (Ctrl + U) and then find (Ctrl + F) the "var affCode". Let me know what you see.

When testing this on the console, as well as the source, the affCode variable is set correctly, the problem is that instead of its content, "25147" is the one used when you click the button.

This is what made me think the scripts were being loaded by the browser/panel at the same time, which would result in the undefined check always being true when its first ran, making It ignore the changed "var affCode", however this doesn't make much sense does it? Not sure what else could be causing it, removing the check makes the script use the updated affCode iirc (on my test yesterday, I'll try one tomorrow and see how it goes).

**Comment by PlanetTheCloud** [comment]
It should be loaded in order. As long as you placed the affcode definition first before loading the script, it is already defined and would be used. I believe there might be issues with the panel being cached or something. That's why we need to get the response or maybe visit the panel ourselves.

**Comment by 4yx** [comment]
@finley541 could you please confirm it is working?
(Do not use our CDN yet, as it seems to be bugged, just use jsDelivr or from your own server)
