### ISSUE TITLE
Element Changer will broken with other language in vP

### ISSUE THREAD

**Issue by ImLoadingUuU** [WybeNetwork/VistaPanel-Customizations#25]

**Comment by 4yx** [comment]
This is unfortunately expected, as Element Changer searches and modifies the elements based on their appearance name, which changes when the language is changed, therefore resulting in the script not finding the element it needs to modify.

I can't think of a way where translations could be implemented into the script so that it looks for them as well, so this takes me back to my early implementation with the numerical system (https://github.com/WybeNetwork/VistaPanel-Customizations/tree/baab54dfe7686bf95ac22cba304528a8110d0965/element-changer) which _should_ work, but was very complicated for the average user and inefficient so it was scrapped.

Not sure how to proceed on this.

**Comment by PlanetTheCloud** [comment]
Wow, really? I guess it's understandable but as @4yx mentioned, we'll have to think of a system so it's easier on the end user.

**Comment by PlanetTheCloud** [comment]
Also another note is that the numerical system might  break when new features are added, messing up the ordering. A way to check that and remove thw correct element is required. Right now I have the idea to use the icons as anchor points, but I'll have to check on it tomorrow.

**Comment by PlanetTheCloud** [comment]
Fixed it, and updated the documentation as well. 
Thanks for reporting.

**Comment by 4yx** [comment]
Out of curiosity, how is this less prone to breaking compared to the numerical system? Maybe with the ordering as you mention but this still suffers from the original issue, oh well can't have everything.
